[package]
name = "mandelbrot-wasm-rs"
version = "0.1.0"
authors = ["Tamaki Mizuha <mizyoukan@outlook.com>"]

[dependencies]
stdweb = { git = "https://github.com/koute/stdweb", rev = "c9cbbcd" }
num-complex = { version = "0.1.42", default-features = false }
